services:
  alert-send-app:
    container_name: alert-send-app
    image: alert-send:latest
    build:
      context: ..
      dockerfile: ./docker/Dockerfile
    ports:
      - "7530:7530"
    volumes:
      - C:/Users/domin/OneDrive/Desktop/config:/config
    networks:
      - alert-send-shared

networks:
  alert-send-shared:
    external: true
    attachable: true